### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by PooLP** [estruyf/react-handlebars-search#13]
Hi,

With the latest version i have this error :

`Warning - [webpack] 'dist':
./node_modules/handlebars-helpers/lib/utils/utils.js
3:34-41 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
    at CommonJsRequireContextDependency.getWarnings (D:\_sharepoint\_thirdParty\react-handlebars-search\node_modules\webpack\lib\dependencies\CommonJsRequireContextDependency.js:27:4)
    at Compilation.reportDependencyErrorsAndWarnings (D:\_sharepoint\_thirdParty\react-handlebars-search\node_modules\webpack\lib\Compilation.js:694:24)
    at Compilation.finish (D:\_sharepoint\_thirdParty\react-handlebars-search\node_modules\webpack\lib\Compilation.js:552:9)
    at applyPluginsParallel.err (D:\_sharepoint\_thirdParty\react-handlebars-search\node_modules\webpack\lib\Compiler.js:506:17)
    at D:\_sharepoint\_thirdParty\react-handlebars-search\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (D:\_sharepoint\_thirdParty\react-handlebars-search\node_modules\webpack\lib\Compilation.js:498:11)
    at processModuleDependencies.err (D:\_sharepoint\_thirdParty\react-handlebars-search\node_modules\webpack\lib\Compilation.js:468:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)`

Do you have any idea where this comes from?

Thanks,
PooLP

**Comment by estruyf** [comment]
Interesting, I saw this also in VSTS. This related to the handlebar helpers and they way how they include helpers. This should have been fixed by the changes made in the `gulpfile.js`.

Which version of node.js are you using?

**Comment by PooLP** [comment]
6.11.4 and if comment the new gulp task to check environment, it work.

**Comment by estruyf** [comment]
Yes, but that way you cannot debug the TS files.

**Comment by estruyf** [comment]
Seems to only occur on a Windows machine. So I found the issue and changed the configuration a bit.

Can you test out the configuration of the DEV branch? https://github.com/estruyf/react-handlebars-search/blob/dev/gulpfile.js

**Comment by PooLP** [comment]
it's working ! and debugging in VSC via Chrome works on .ts files. Thanks
